### ISSUE TITLE
example please

### ISSUE THREAD

**Issue by goldalworming** [netanelgilad/angular-cesium#18]
Hi, thank you create the directives

can you add example please, how to put centering map in controller.

adding billboard returns nothing in map, just show the globe and I can do nothing.
can you add simple tutorial to basic feature

**Comment by bipol** [comment]
Hey @goldalworming: i'll work on creating a new example for you.

**Comment by bipol** [comment]
Here is a quick example showing layers and billboards - hope this helps.  I'll add the new items and some more documentation in the future - it's probably best to use a baselayerpicker when user terrain providers or layers in order to manage them more easily.
https://github.com/bipolalam/ac-angular-cesium-example
